# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

variables:
- name: buildConfiguration 
  value: 'Release'
- name: solution 
  value: '**\*.sln'
- name: buildPlatform
  value: 'any cpu'
- group: Pipelines Variables


pool:
    vmImage: 'windows-latest'

steps:
- task: mirror-git-repository-vsts-task@1
  inputs:
    sourceGitRepositoryUri: 'https://dev.azure.com/kamilmrzyglod/Smart%20home/_git/SmartHome.Devices'
    sourceGitRepositoryPersonalAccessToken: $(DevOpsReposAccessToken)
    destinationGitRepositoryUri: 'https://github.com/kmrzyglod/SmartHome.Devices.git'
    destinationGitRepositoryPersonalAccessToken: $(GitHubAccessToken)
- task: NuGetCommand@2
  inputs:
    command: 'restore'
    restoreSolution: '**/*.sln'
    feedsToUse: 'select'
- task: InstallnFBuildComponents@1
  displayName: Install nanoFramework MSBuild components

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    platform: '$(buildPlatform)'
    msbuildArgs: '/p:PublicRelease=true'
    configuration: '$(buildConfiguration)'


